### ISSUE TITLE
Subscription Watch dashboard card hover and click

### ISSUE THREAD

**Issue by bclarhk** [RedHatInsights/insights-dashboard#130]
The hover target area is too small. Can we target this div (for each product)
![image](https://user-images.githubusercontent.com/32572198/79771021-358ca280-82fc-11ea-94d1-e40dfc55599d.png)

The product name should be a blue link to the product page in Subscription Watch.

**Comment by cdcabrera** [comment]
Relates https://github.com/RedHatInsights/curiosity-frontend/issues/266
