### ISSUE TITLE
Max height on cards in the top row 

### ISSUE THREAD

**Issue by kybaker** [RedHatInsights/insights-dashboard#161]
Cards in the top row are showing tons of empty space which pushes down the cards below. I suspect they just resize to accommodate for browser height. Ideally the top row of cards would expand just the height of the content of the cards.

![image](https://user-images.githubusercontent.com/2205964/84941458-7102dd80-b0af-11ea-8733-2de0358ca3f6.png)

**Comment by leSamo** [comment]
Closing as Dashboard has been redesigned since this ticket was created 2 years ago and it does not have any problems with unused blank space inside cards anymore.
