### ISSUE TITLE
Improve responsive behavior of dashboard

### ISSUE THREAD

**Issue by ncameronbritt** [RedHatInsights/insights-dashboard#26]
I noticed in the demo that even at very wide viewports, there are always 3 cards in a row on the dashboard. Those cards look very anemic with so much space in them. I think cards should have some max width and that the cards should flow into available space. The [PF4 Gallery layout](https://pf4.patternfly.org/layouts/Gallery/examples/) should help this responsive behavior.

Screenshot:
![screen shot 2019-02-22 at 10 53 27 am](https://user-images.githubusercontent.com/8974593/53253841-29716a80-3690-11e9-9625-b30835de0ab0.png)

cc @RedHatInsights/uxd

**Comment by jeperry** [comment]
Agreed. The PF4 Gallery layout should be used for all card layout pages platform wide.

**Comment by ryelo** [comment]
Thanks for bringing this up @jeperry @ncameronbritt. Should be on CI.

**Comment by ncameronbritt** [comment]
Thanks for knocking it out so quickly @ryelo!
