### ISSUE TITLE
Advisor card updates

### ISSUE THREAD

**Issue by christiemolloy** [RedHatInsights/insights-dashboard#77]
Based on Kyle's updated mocks:
<img width="663" alt="Screen Shot 2020-03-25 at 9 41 19 AM" src="https://user-images.githubusercontent.com/20118816/77542613-d9f60300-6e7c-11ea-86a9-a0eacd8dbfb7.png">

**- Add in the Download Report button to the header**
**- Add in the "InfoInline" component to the header and populate it with the "new rules"**
**- Ask Kyle above what number determines whether this is critical and needs the critical icon to the left of it**

<img width="282" alt="Screen Shot 2020-03-25 at 9 44 15 AM" src="https://user-images.githubusercontent.com/20118816/77542923-4c66e300-6e7d-11ea-9283-c592100dfe6e.png">

**- Update bottom link so that it just includes data for number of systems with rule hits**

<img width="293" alt="Screen Shot 2020-03-25 at 9 45 25 AM" src="https://user-images.githubusercontent.com/20118816/77543024-6ef8fc00-6e7d-11ea-8efe-ababc4b46874.png">

**Comment by AllenBW** [comment]
Api doesn't support a notion of new rules, we can sort by date tho 🤷‍♂
