### ISSUE TITLE
Add Remediations Empty State

### ISSUE THREAD

**Issue by christiemolloy** [RedHatInsights/insights-dashboard#79]
Kyle's new mocks: https://marvelapp.com/a5c8bcg/screen/67195889 include the new empty state for the remediations card. Need to add this.

<img width="346" alt="Screen Shot 2020-03-25 at 9 53 17 AM" src="https://user-images.githubusercontent.com/20118816/77544210-1e829e00-6e7f-11ea-945a-741e6d67f255.png">

**Comment by ryelo** [comment]
Fixed by #112
