### ISSUE TITLE
Empty state for Subscription watch when there is 0 data

### ISSUE THREAD

**Issue by christiemolloy** [RedHatInsights/insights-dashboard#96]
Need to add this empty state, 
also if there is only 1 progress bar showing data, is this ok?

<img width="370" alt="Screen Shot 2020-04-01 at 11 04 56 AM" src="https://user-images.githubusercontent.com/20118816/78169147-f830a580-741e-11ea-989c-8ca753541973.png">

<img width="367" alt="Screen Shot 2020-04-01 at 11 05 26 AM" src="https://user-images.githubusercontent.com/20118816/78169150-f8c93c00-741e-11ea-9fff-df85a4536367.png">

**Comment by bclarhk** [comment]
recent changes should have resolved this, this should be reconfirmed and closed accordingly

**Comment by cdcabrera** [comment]
Can confirm recent changes resolved this original issue. Another parallel issue has popped up and related to the "opt in"

![test4](https://user-images.githubusercontent.com/3761375/80020668-678e3800-84a7-11ea-88c7-26838dce2ef7.jpg)
